project_params:
  version: 0.1.0
  execution_runs: 1

evolutionary_learning_params:
  population_size: [5, 10, 15]
  crossover_percentage: [0.2, 0.5, 0.7]
  mutation_percentage: [0.15, 0.25, 0.35]
  mutation_rate: [0.05, 0.3, 0.65]
  max_generations: [5, 10, 15]
  fitness_lambda: [0.1, 0.25, 0.8]
  lambda_factor: [0.05,0.1,0.3]

evolutionary_learning_methods:
  chromosome_representation: [1D,2D,dual]
  crossover_methods: [single_point_crossover,
                      two_point_crossover,
                      three_point_crossover,
                      uniform_crossover,
                      commonality_based_crossover]
  mutation_methods: [bit_flip_mutation, bit_string_mutation]
  parent_selection_method: [roulette_wheel_selection, tournament_selection, random_selection]
  diversity_only_error: True

multiple_classification_models_params:
  fusion_method: [majority_voting,weighted-average]
  heterogeneous_classifiers: True
  cross_val: [5]
  evaluation_metric: [f1_micro,f1_macro,recall]

dynamic_ensemble_selection_params:

data_params:
  dataset: [iris,digits,breast_cancer,wine]
  path: data/
  normalization: [MinMax, Standardization, Normalization]

evaluation_params:
  score_metric: [f1_micro,f1_macro,recall]
  path: results
  error_analysis: True
  error_analysis_params: [lambda_factor, population_size,crossover_percentage,
                          mutation_percentage,mutation_rate,
                          fitness_lambda,crossover_methods,
                          mutation_methods,parent_selection_method,
                          dataset, normalization]




